[package]
name = "yahs"
description = "Yet Another HAB Simulator"
authors = ["Philip Linden <lindenphilipj@gmail.com>"]
version = "0.1.0"
edition = "2021"
readme = "README.md"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_env_logger = "0.5.0"
libm = "0.2.1"
toml = "0.8.10"
clap = { version = "4.1", default-features = false, features = [
    "derive",
    "std",
    "help",
    "usage",
    "error-context",
    "suggestions",
] }
csv = "1.2.1"
serde = { version = "1.0.196", features = ["derive"] }
log = { version = "0.4.20", features = ["release_max_level_debug"] }
egui = { version = "0.26.2", features = ["log", "serde"], optional = true }
egui_plot = { version = "0.26.2", features = ["serde"], optional = true }
eframe = { version = "0.26.2", features = ["persistence"], optional = true }

[features]
default = ["gui"]
gui = ["egui", "egui_plot", "eframe"]

[[bin]]
name = "yahs"
path = "src/main.rs"
