[package]
name = "yahs"
description = "Yet Another HAB Simulator"
authors = ["Philip Linden <lindenphilipj@gmail.com>"]
version = "0.1.0"
edition = "2021"
readme = "README.md"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4", features = ["release_max_level_debug"] }
pretty_env_logger = "0.4.0"
libm = "0.2.1"
toml = "0.7"
serde = { version = "1.0.157", features = ["derive", "std"] }
clap = { version = "4.1", default-features = false, features = [
    "derive",
    "std",
    "help",
    "usage",
    "error-context",
    "suggestions",
] }
csv = "1.2.1"
anyhow = "1.0.70"

[[bin]]
name = "yahs"
path = "src/main.rs"
