[package]
name = "yahs"
description = "Yet Another HAB Simulator"
authors = ["Philip Linden <lindenphilipj@gmail.com>"]
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "Apache-2.0"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4", features = ["release_max_level_debug"] }
pretty_env_logger = "0.4.0"
libm = "0.2.1"
toml = "0.5"
clap = { version = "4.1.8", features = ["derive"] }
sysinfo = "0.28.2"
csv = "1.2.1"
