[package]
name = "yahs"
description = "Yet Another HAB Simulator"
authors = ["Philip Linden <lindenphilipj@gmail.com>"]
version = "0.2.0"
edition = "2021"
readme = "README.md"
license-file = "LICENSE"

[features]
default = ["gui"]
gui = [
    "egui",
    "egui_extras",
    "egui_plot",
    "eframe",
    "emath",
]

[dependencies]
pretty_env_logger = "0.5.0"
libm = "0.2.1"
toml = "0.8.10"
clap = { version = "4.1", default-features = false, features = [
    "derive",
    "std",
    "help",
    "usage",
    "error-context",
    "suggestions",
] }
csv = "1.2.1"
serde = { version = "1.0.196", features = ["derive"] }
log = { version = "0.4.20", features = ["release_max_level_debug"] }
egui = { version = "0.26.2", features = ["log", "serde"], optional = true }
egui_plot = { version = "0.26.2", features = ["serde"], optional = true }
eframe = { version = "0.26.2", features = ["persistence"], optional = true }
emath = { version = "0.26.2", optional = true }
egui_extras = { version = "0.26.2", features = [
    "chrono",
    "datepicker",
    "file",
], optional = true }
ultraviolet = { version = "0.9.2", features = ["serde"] }

[[bin]]
name = "yahs"
path = "src/main.rs"
