# balloon properties
balloon_part_id = "HAB_1200"
lift_gas_species = "Helium"
lift_gas_mass_kg = 1.5

# payload box properties
dry_mass_kg = 1.427
box_area_m2 = 0.04
box_drag_coeff = 2.1

# parachute properties
parachute_area_m2 = 1.1
parachute_drag_coeff = 1.3
parachute_open_altitude_m = 18_000.0
